name: Link Checker

on:
  push:
    branches:
      - main
      - master
    paths:
      - "**/*.md"
      - ".github/workflows/link-checker.yaml"
  pull_request:
    branches:
      - main
      - master
    paths:
      - "**/*.md"
  workflow_dispatch:

jobs:
  link-checker:
    name: 🔗 Link Checker
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code
        uses: actions/checkout@v6

      - name: 🔍 Check Links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress "**/*.md"
          fail: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
